name: docker build target
description: docker build target and scan image

# NOTE: Fixes "Error: Resource not accessible by integration"
# permissions:
#   contents: read
#   security-events: write

inputs:
  image_tag:
    description: The image tag
    required: true

  fail-build:
    description: Fail the build if vulnerabilities are found
    required: false
    default: "false"

runs:
  using: composite

  steps:
    - name: Scan ${{ inputs.image_tag }}
      uses: anchore/scan-action@v3
      id: scan
      with:
        image: ${{ inputs.image_tag }}
        fail-build: ${{ inputs.fail-build }}
        output-format: sarif

    - name: Upload SARIF
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}
